module.exports = { "1": "Returned error: VM Exception while processing transaction: revert You have a pending found, make rebidding -- Reason given: You have a pending found, make rebidding." ,
                   "2": "Returned error: VM Exception while processing transaction: revert The amount is not enough to overcome the previous bid -- Reason given: The amount is not enough to overcome the previous bid.",
                   "3": "Returned error: VM Exception while processing transaction: revert HighestBidder cannot make rebidding -- Reason given: HighestBidder cannot make rebidding.",
                   "4": "Returned error: VM Exception while processing transaction: revert This function only work if you have a overcame bid -- Reason given: This function only work if you have a overcame bid.",
                   "5": "Returned error: VM Exception while processing transaction: revert Auction isn't ended yet -- Reason given: Auction isn't ended yet.",
                   "6": "Returned error: VM Exception while processing transaction: revert Is too late to make a bid. The auction has ended -- Reason given: Is too late to make a bid. The auction has ended.",
                   "7": "Returned error: VM Exception while processing transaction: revert You don't have any funds on this contract -- Reason given: You don't have any funds on this contract.",
                   "8": "Returned error: VM Exception while processing transaction: revert Only beneficiary can call this function -- Reason given: Only beneficiary can call this function.",
                   "9": "Returned error: VM Exception while processing transaction: revert You don't have pending founds, make a bid instead -- Reason given: You don't have pending founds, make a bid instead.",
                   "10": "Returned error: VM Exception while processing transaction: revert Only lone funders can retire pending funds before end of auction -- Reason given: Only lone funders can retire pending funds before end of auction.",
                   "11": "Returned error: VM Exception while processing transaction: revert Auction isn't ended yet",
                   "12": "Returned error: VM Exception while processing transaction: revert Beneficiary cannot use this function -- Reason given: Beneficiary cannot use this function.",
                   "13": "Returned error: VM Exception while processing transaction: revert You are the winner! The price is yours -- Reason given: You are the winner! The price is yours."
                 };